name: moje_miasto
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.2.1
  flutter_svg: ^1.1.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  cached_network_image: ^3.2.2
  json_annotation: ^4.6.0
  equatable: ^2.0.5
  diacritic: ^0.1.3
  animated_bottom_navigation_bar: ^1.1.0
  carousel_slider: ^4.1.1
  dialog_flowtter: ^0.3.3
  # firebase_core: ^2.0.0
  # firebase_storage: ^0.3.2
  # firebase_storage: ^11.0.0
  image_picker: ^0.8.6
  uuid: ^3.0.6
  meta: ^1.7.0
  flow_builder: ^0.0.9
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.1
  cloud_firestore: ^3.5.1

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.2
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  json_serializable: ^6.3.2

flutter:
  uses-material-design: true

  assets:
    - images/screens/
    - images/screens/language_selector/
    - images/screens/forgot_password/
    - images/screens/info/
    - images/screens/create_account/avatar_selector/
    - images/screens/create_account/
    - images/app/
    - images/screens/tos/
    - images/screens/ca_more_info/account_type_selector/
    - images/screens/home_screen/features_carousel/
    - images/screens/add_school_screen/
    - images/screens/add_help_entry_screen/
    - images/screens/hobby_i_zainteresowania_screen/
    - images/screens/konkursy_i_olimpiady_screen/
    - lib/screens/account_creation_screens/ca_more_info/widgets/city_picker/data/
    - assets/dialog_flow_auth.json

  # TODO: Remove unused fonts from the app
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
